### PR TITLE
fix: autocancel typo

### PR DESCRIPTION
**Pull request by Max87ZA**
autocancel now removes notification after user clicks on it in notification center

### CODE REVIEW

**Comment by macasfaj** [comment]
This PR is great!! Will we have a new release 4.2.2 soon? Thanks!

**Comment by macasfaj** [comment]
@Max87ZA Tested on real device, Android 14, when I click the notification, it's not removes, auto cancel is not working :(

**Comment by Max87ZA** [comment]
@macasfaj Hello, I tested it too and it worked perfectly. Did you set autocancel: true? It worked for at least when app was in background/killed…

**Comment by macasfaj** [comment]
Hi, thanks for your answer, maybe I'm wrong. I'll be back to you ASAP.

**Comment by macasfaj** [comment]
I cleaned the project and tested carefully and you're right, It works like a charm. Great PR!! Thanks! :)

**Comment by Max87ZA** [comment]
I’m happy that it works to you, you’re welcome

**Pull request merged**
